---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: fashion-bestseller
      name: fashion-bestseller
    spec:
      ports:
        - name: http
          port: 8082
          targetPort: 8082
      selector:
        app: fashion-bestseller
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: fashion-bestseller-deployment
    spec:
      selector:
        matchLabels:
          app: fashion-bestseller
      template:
        metadata:
          labels:
            app: fashion-bestseller
        spec:
          containers:
          - name: fashion-bestseller
            image: tanzukorea.azurecr.io/spring-cloud-k8s-demo/fashion-bestseller:1.0-SNAPSHOT
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            imagePullPolicy: Always
            readinessProbe:
              httpGet:
                port: 8082
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8082
                path: /actuator/health/liveness
            ports:
            - containerPort: 8082
