---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: gateway
      name: gateway
    spec:
      ports:
        - name: http
          port: 8070
          targetPort: 8070
      selector:
        app: gateway
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gateway-deployment
    spec:
      selector:
        matchLabels:
          app: gateway
      template:
        metadata:
          labels:
            app: gateway
        spec:
          containers:
          - name: gateway
            image: tanzukorea.azurecr.io/spring-cloud-k8s-demo/gateway:1.0-SNAPSHOT
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            imagePullPolicy: Always
            readinessProbe:
              httpGet:
                port: 8070
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8070
                path: /actuator/health/liveness
            ports:
            - containerPort: 8070
