kind: ConfigMap
apiVersion: v1
metadata:
  name: toys-bestseller
  labels:
    "spring.cloud.kubernetes.config": "true"
data:
  chaos.monkey.enabled: "false"
  chaos.monkey.assaults.latencyActive: "true"
  spring.profiles.active: "kubernetes"
  spring.cloud.kubernetes.discovery.enabled: "false"
  spring.cloud.kubernetes.discovery.discovery-server-url: "http://spring-cloud-kubernetes-discoveryserver"
