---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: toys-bestseller
      name: toys-bestseller
    spec:
      ports:
        - name: http
          port: 8081
          targetPort: 8081
      selector:
        app: toys-bestseller
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: toys-bestseller-deployment
    spec:
      selector:
        matchLabels:
          app: toys-bestseller
      template:
        metadata:
          labels:
            app: toys-bestseller
        spec:
          containers:
          - name: toys-bestseller
            image: tanzukorea.azurecr.io/spring-cloud-k8s-demo/toys-bestseller:1.0-SNAPSHOT
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            imagePullPolicy: Always
            readinessProbe:
              httpGet:
                port: 8081
                path: /actuator/health/readiness
            #  initialDelaySeconds: 10
            #  timeoutSeconds: 2
            #  periodSeconds: 3
            #  failureThreshold: 1
            livenessProbe:
              httpGet:
                port: 8081
                path: /actuator/health/liveness
            #  initialDelaySeconds: 20
            #  timeoutSeconds: 2
            #  periodSeconds: 8
            #  failureThreshold: 1
            ports:
            - containerPort: 8081

#java -jar -Dspring.profiles.active=prod application.jar
#java -jar application.jar --spring.profiles.active=prod --spring.config.location=c:\config
# didn't work
#args: ["-c", "--spring.main.cloud-platform=kubernetes --spring.profiles.active=kubernetes"]
            #- name: JAVA_OPTS
            #  value: "--Dspring.main.cloud-platform=kubernetes --Dspring.profiles.active=kubernetes"
