apiVersion: v1
data:
  application.yaml: |-
    spring:
      cloud:
        kubernetes:
          configuration:
            watcher:
              refreshDelay: 3
      #rabbitmq:
      #  username: admin
      #  password: password
    logging:
      level:
        org:
          springframework:
            cloud:
              kubernetes: TRACE
    management:
      endpoints:
        web:
          exposure:
            include: "*"
kind: ConfigMap
metadata:
  name: spring-cloud-kubernetes-configuration-watcher
