
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haewons-tanzu/spring-cloud-k8s-config
          defaultLabel: "master"
server:
  port: 8888